CREATE TABLE repository_data_migration_repository (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  migration_job_id BIGINT UNSIGNED NOT NULL,
  source_repository_name VARCHAR(255) NOT NULL,
  target_repository_name VARCHAR(255) NOT NULL,
  target_repository_id BIGINT UNSIGNED NOT NULL,
  format VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  cursor_path VARCHAR(2048) NULL,
  page_size INT UNSIGNED NOT NULL,
  total_assets BIGINT UNSIGNED NOT NULL DEFAULT 0,
  discovered_assets BIGINT UNSIGNED NOT NULL DEFAULT 0,
  migrated_assets BIGINT UNSIGNED NOT NULL DEFAULT 0,
  failed_assets BIGINT UNSIGNED NOT NULL DEFAULT 0,
  claimed_at DATETIME(3) NULL,
  last_error TEXT NULL,
  options_json JSON NOT NULL,
  started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  finished_at DATETIME(3) NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_repo_data_migration_source (migration_job_id, source_repository_name),
  KEY idx_repo_data_migration_status (status, claimed_at, id),
  KEY idx_repo_data_migration_target (target_repository_id),
  CONSTRAINT fk_repo_data_migration_job FOREIGN KEY (migration_job_id) REFERENCES migration_job (id) ON DELETE CASCADE,
  CONSTRAINT fk_repo_data_migration_target FOREIGN KEY (target_repository_id) REFERENCES repository (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE repository_data_migration_asset (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  repository_job_id BIGINT UNSIGNED NOT NULL,
  source_asset_id VARCHAR(100) NULL,
  source_component_id VARCHAR(100) NULL,
  source_path VARCHAR(2048) NOT NULL,
  source_path_hash BINARY(32) NOT NULL,
  format VARCHAR(50) NOT NULL,
  namespace VARCHAR(512) NULL,
  name VARCHAR(512) NULL,
  version VARCHAR(255) NULL,
  asset_kind VARCHAR(100) NULL,
  content_type VARCHAR(255) NULL,
  size BIGINT UNSIGNED NULL,
  source_blob_ref VARCHAR(1024) NULL,
  source_last_updated_at DATETIME(3) NULL,
  source_last_downloaded_at DATETIME(3) NULL,
  source_blob_created_at DATETIME(3) NULL,
  source_blob_updated_at DATETIME(3) NULL,
  source_created_by VARCHAR(255) NULL,
  source_created_by_ip VARCHAR(64) NULL,
  status VARCHAR(50) NOT NULL,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  claimed_at DATETIME(3) NULL,
  migrated_at DATETIME(3) NULL,
  target_component_id BIGINT UNSIGNED NULL,
  target_asset_id BIGINT UNSIGNED NULL,
  target_asset_blob_id BIGINT UNSIGNED NULL,
  last_error TEXT NULL,
  metadata_json JSON NOT NULL,
  discovered_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_repo_data_migration_asset_path (repository_job_id, source_path_hash),
  KEY idx_repo_data_migration_asset_status (status, claimed_at, id),
  KEY idx_repo_data_migration_asset_repo_status (repository_job_id, status, id),
  KEY idx_repo_data_migration_asset_target_asset (target_asset_id),
  KEY idx_repo_data_migration_asset_target_blob (target_asset_blob_id),
  CONSTRAINT fk_repo_data_migration_asset_repo FOREIGN KEY (repository_job_id)
      REFERENCES repository_data_migration_repository (id) ON DELETE CASCADE,
  CONSTRAINT fk_repo_data_migration_asset_component FOREIGN KEY (target_component_id)
      REFERENCES component (id) ON DELETE SET NULL,
  CONSTRAINT fk_repo_data_migration_asset_asset FOREIGN KEY (target_asset_id)
      REFERENCES asset (id) ON DELETE SET NULL,
  CONSTRAINT fk_repo_data_migration_asset_blob FOREIGN KEY (target_asset_blob_id)
      REFERENCES asset_blob (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
